name: Lint
on: push

permissions:
  checks: write

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run Revive Action
      uses: morphy2k/revive-action@f5a802ec818edc02e57673498a630788d97a99c3
      with:
        config: revive.toml
        path: "./error/..."
        exclude: "error2.go;error3.go"
