name: Lint
on: push

permissions:
  checks: write

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run Revive Action
      uses: morphy2k/revive-action@2a9a601c4c69cb0a0304b61b85a640e3cbdc99a9
      with:
        config: revive.toml
        path: "./error/..."
        exclude: |
          error/error2.go
          error/error3.go
