name: Lint
on: push

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run Revive Action
      uses: morphy2k/revive-action@go-github-v31
      with:
        config: revive.toml
        path: "./errors/..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
