name: Lint
on: push

permissions:
  checks: write

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run Revive Action
      uses: docker://morphy/revive-action:v2
      with:
        config: revive.toml
        # path: "./error/..."
