name: Lint
on: push

permissions:
  checks: write

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Revive Action
      uses: morphy2k/revive-action@fix-missing-go-install
      with:
        config: revive.toml
        path: "./error/..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
