name: Lint
on:
  push:
    paths:
      - '*.go'
      - 'revive.toml'
      - '.github/workflows/lint.yaml'
    tags:
      - '!refs/tags/*'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run Revive Action
      uses: morphy2k/revive-action@feature/custom-path
      with:
        config: revive.toml
        path: "./errors/..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
