name: Lint
on: push

permissions:
  checks: write

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run Revive Action
      uses: morphy2k/revive-action@26f09a80bcadf30023da5237616f4571a80e7703
      with:
        config: revive.toml
        path: "./error/..."
